### PR TITLE
#276 added file extension filters on import

### LINKED ISSUE #276: fileextension filters on import
if only valid file extensions (`.qid` or `.qco` according to the task) are visible by default, the probability that a user imports the wrong file or with the wrong dialog (identity vs contact vs contacts) is lower and we can identitfy real problems more easily with less crash report pollution.

### PR DESCRIPTION
**Pull request by taynaps**
closed #276

### CODE REVIEW

File: src/main/java/de/qabel/desktop/ui/contact/ContactController.java [hunk 1]
```diff
@@ -127,14 +129,16 @@ private void showActionlog(Contact contact) {
...
+        chooser.getExtensionFilters().add(qcoExtensionFilter);
+        File file = chooser.showOpenDialog(contactList.getScene().getWindow());
         try {
-            FileChooser chooser = new FileChooser();
-            chooser.setTitle(resourceBundle.getString("contactDownloadFolder"));
-            File file = chooser.showOpenDialog(contactList.getScene().getWindow());
-
             importContacts(file);
             loadContacts();
-        } catch (NullPointerException ignored) {
```
Comment (jmt85) [inline src/main/java/de/qabel/desktop/ui/contact/ContactController.java]: why do not ignore the null pointer exception?

**Comment by Rehwanne** [comment]
retest this please
