### PR TITLE
Quota display

### LINKED ISSUE #184: show quota from accounting server

### LINKED ISSUE #220: Description for Quota
The Quota is not self-explanatory. It needs text.

comes from wulfs mock ups

### LINKED ISSUE #409: Error to delete contact item
When clicking on the delete button, the contact item is deleted, but it shows an exception that the contact was not found.

### PR DESCRIPTION
**Pull request by nnice**
resolves #220 
fixes #409 
resolves #184

### CODE REVIEW

**Comment by nnice** [comment]
resolves #184

File: src/main/java/de/qabel/desktop/ui/LayoutController.java [hunk 1]
```diff
@@ -176,10 +185,64 @@ public void initialize(URL location, ResourceBundle resources) {
...
+    }
+
+    /**
+     * @param usedQuota
+     * @param availableQuota
+     * @return
+     */
+    int ratioByDiff(long usedQuota, long availableQuota) {
+        long freeSpace = availableQuota - usedQuota;
+        return (int) (usedQuota / (double) availableQuota * 100);
```
Comment (JoGir) [inline src/main/java/de/qabel/desktop/ui/LayoutController.java]: freeSpace / (available*100) ?

File: src/main/java/de/qabel/desktop/ui/LayoutController.java [hunk 2]
```diff
@@ -176,10 +185,64 @@ public void initialize(URL location, ResourceBundle resources) {
         newMessageIndicator.visibleProperty().bind(newMessageIndicator.textProperty().isNotEqualTo("0"));
     }
 
+    private void fillQuotaInformation() {
+        try {
+            quotaState = boxClient.getQuotaState();
+        } catch (IOException | QblInvalidCredentials e) {
+            e.printStackTrace();
```
Comment (JoGir) [inline src/main/java/de/qabel/desktop/ui/LayoutController.java]: May some user feedback like 'Cant load quota'... Catch with stackTrace only is evil...

**Comment by nnice** [comment]
@thechauffeur what do we do if the quota cannot be fetched from server for some reasons? 
Hide the Display?, or do we fill them with some sort of unavalable stuff?

**Comment by thechauffeur** [comment]
Show i18n version of unavailable.

The commit message after your question suggests you already implemented a solution to your question. You can just leave it that way.

File: src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java [hunk 3]
```diff
@@ -1,14 +1,37 @@
 package de.qabel.desktop.ui;
 
+import com.sun.org.apache.xpath.internal.operations.Quo;
```
Comment (audax) [inline src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java]: *

**Comment by audax** [comment]
Please merge with master

File: src/main/java/de/qabel/desktop/ui/LayoutController.java [hunk 4]
```diff
@@ -176,10 +176,66 @@ public void initialize(URL location, ResourceBundle resources) {
...
+
+        if (size < sizeMo)
+            return df.format(size / sizeKb) + " Kb";
+        else if (size < sizeGB)
+            return df.format(size / sizeMo) + " MB";
+        else if (size < sizeTerra)
+            return df.format(size / sizeGB) + " GB";
+
+        return "";
+    }
```
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/ui/LayoutController.java]: Did you copy&paste this code? Then please read it, think about it and ... at least test it

Comment (enkore) [inline src/main/java/de/qabel/desktop/ui/LayoutController.java]: This kind of function should imho be in a utility class/package/file somewhere, be public + reusable. Also makes testing much easier.

[Python code that works and does the right thing™ - probably somewhere to be found in Java/Kt as well](https://github.com/borgbackup/borg/blob/master/src/borg/helpers.py#L614)

File: src/main/java/de/qabel/desktop/ui/LayoutController.java [hunk 5]
```diff
@@ -176,10 +176,66 @@ public void initialize(URL location, ResourceBundle resources) {
...
+        quotaDescription.setText(quotaDescriptionText);
+    }
+
+    int ratioByDiff(long usedQuota, long availableQuota) {
+        return (int) (usedQuota / (double) availableQuota * 100);
+    }
+
+    String quotaDescription(long usedQuota, long availableQuota) {
+        long diff = availableQuota - usedQuota;
+        return getStringSizeLengthFile(diff) + " free / " + getStringSizeLengthFile(availableQuota);
```
Comment (enkore) [inline src/main/java/de/qabel/desktop/ui/LayoutController.java]: If the app should support l10n, then "free" shouldn't be hard coded I think.

File: src/main/java/de/qabel/desktop/ui/LayoutController.java [hunk 6]
```diff
@@ -176,10 +176,66 @@ public void initialize(URL location, ResourceBundle resources) {
...
+    @FXML
+    BorderPane quotaBlock;
+    @FXML
+    Label quota;
+    @FXML
+    Label provider;
+    @FXML
+    Label quotaDescription;
+    @Inject
+    BoxClient boxClient;
```
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/ui/LayoutController.java]: Why did you move these variables down?
Default (=expected) structure of a class is
```
class signature
static variables
instance variables
constructor(s)
methods
```
isn't it?

File: src/main/java/de/qabel/desktop/ui/LayoutController.java [hunk 7]
```diff
@@ -176,10 +176,66 @@ public void initialize(URL location, ResourceBundle resources) {
...
+
+    private void fillQuotaInformation() {
+        try {
+            quotaState = boxClient.getQuotaState();
+        } catch (IOException | QblInvalidCredentials e) {
+            alert(e);
+        }
+        if (quotaState == null) {
```
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/ui/LayoutController.java]: as far as I can see, this happens only in the catch-case of `boxClient.getQuotaState();`, move it there to clear your intent. The if gets unneccessary then

File: src/main/java/de/qabel/desktop/ui/LayoutController.java [hunk 8]
```diff
@@ -176,10 +176,66 @@ public void initialize(URL location, ResourceBundle resources) {
...
+            quotaBlock.setVisible(false);
+            quotaDescription.setVisible(false);
+            return;
+        }
+
+        int ratio = ratioByDiff(quotaState.getSize(), quotaState.getQuota());
+        String quotaDescriptionText = quotaDescription(quotaState.getSize(), quotaState.getQuota());
+        quota.setText(ratio + "%");
+        provider.setMinWidth(ratio);
```
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/ui/LayoutController.java]: `provider` is not very descriptive, especially in this context. What does it represent? Please try to find a better name

File: src/main/java/de/qabel/desktop/ui/LayoutController.java [hunk 9]
```diff
@@ -176,10 +176,66 @@ public void initialize(URL location, ResourceBundle resources) {
...
+        quotaDescription.setText(quotaDescriptionText);
+    }
+
+    int ratioByDiff(long usedQuota, long availableQuota) {
+        return (int) (usedQuota / (double) availableQuota * 100);
+    }
+
+    String quotaDescription(long usedQuota, long availableQuota) {
+        long diff = availableQuota - usedQuota;
```
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/ui/LayoutController.java]: `free` seems to fit better than diff. This method is `quotaDescription` and not `concat` or `sum` ... even if the result is some kind of a sum of strings.

File: src/test/java/de/qabel/desktop/ui/AbstractControllerTest.java [hunk 10]
```diff
@@ -131,11 +134,13 @@ public void setUp() throws Exception {
...
         diContainer.put("aboutFilesContent", new FilesAbout());
 
+        diContainer.put("boxClient", boxClient);
+
         syncDaemon = new SyncDaemon(new SimpleListProperty<>(), new FakeSyncerFactory());
         diContainer.put("syncDaemon", syncDaemon);
         diContainer.put("accountingUri", new URI("http://localhost:9696"));
 
-        AfterburnerInjector.setConfigurationSource(key -> diContainer.get((String)key));
+        AfterburnerInjector.setConfigurationSource(key -> diContainer.get((String) key));
```
Comment (julianseeger) [inline src/test/java/de/qabel/desktop/ui/AbstractControllerTest.java]: You should set your IDE to only reformat vcs modified lines. Your diffs contain a lot of only reformatted code

File: src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java [hunk 11]
```diff
@@ -1,15 +1,57 @@
...
 
     public static final int MIN_ITEM_COUNT = 2;
 
+    //same values as the BoxClientStub
+    private QuotaState expectedQuotaState = new QuotaState(24, 100);
+
+    @Test
+    public void testQuotaDescription() {
+        String expected = "668 MB free / 954 MB";
+        long availableQuota = 1000000000L;
```
Comment (julianseeger) [inline src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java]: extract constant -> `long 954 MB = ....L;`

File: src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java [hunk 12]
```diff
@@ -1,15 +1,57 @@
...
+        QuotaState quota = controller.boxClient.getQuotaState();
+
+        String expectedDesc = controller.quotaDescription(expectedQuotaState.getSize(), expectedQuotaState.getQuota());
+        int expectedRatio = controller.ratioByDiff(expectedQuotaState.getSize(), expectedQuotaState.getQuota());
+
+        assertEquals(expectedQuotaState.getQuota(), quota.getQuota());
+        assertEquals(expectedQuotaState.getSize(), quota.getSize());
+        assertEquals(expectedRatio + "%", controller.quota.getText());
+        assertEquals(expectedRatio, (int) controller.provider.getMinWidth());
+        assertEquals(expectedDesc, controller.quotaDescription.getText());
```
Comment (julianseeger) [inline src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java]: Compare your test to this alternative version:
```JAVA
@Test
public void fillsQuotaInformation() throws Exception {
    boxClientStub.setQuotaState(new QuotaState(24, 100));
    createController();
    
    assertEquals("24%", controller.quota.getText());
    assertEquals(24, controller.provider.getMinWidth());
    assertEquals("24 B free / 100 B", controller.quotaDescription.getText());
}
```

Which one is more obvious in that we want to test that the controller initializes those three values? (%, description and width).
Imho using explicit (useful) values is always better than calculating your expectations. Because you should know what you expect in a test.

File: src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java [hunk 13]
```diff
@@ -1,15 +1,57 @@
...
+        long usedQuota = 300000000L;
+        int ratio = createController().ratioByDiff(usedQuota, availableQuota);
+
+        assertEquals(expectedRatio, ratio);
+    }
+
+    @Test
+    public void testFillQuotaInformation() throws IOException, QblInvalidCredentials {
+        LayoutController controller = createController();
+        QuotaState quota = controller.boxClient.getQuotaState();
```
Comment (julianseeger) [inline src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java]: You don't need to test that. The BoxClientImpl is tested in the core and this is a stub anyways.

File: src/main/java/de/qabel/desktop/ui/LayoutController.java (hunk 4 above)
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/ui/LayoutController.java]: right. IIRC we already got a humanize lib for times integrated. I would suggest https://github.com/mfornos/humanize for other stuff. That would also keep the `b/B` konsistent ;)

File: src/main/java/de/qabel/desktop/ui/LayoutController.java (hunk 5 above)
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/ui/LayoutController.java]: it does (resourceBundle)

File: src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java [hunk 14]
```diff
@@ -1,25 +1,44 @@
...
 import static org.junit.Assert.assertTrue;
 
 public class LayoutControllerTest extends AbstractControllerTest {
 
     public static final int MIN_ITEM_COUNT = 2;
 
+    @Override
+    @Before
+    public void setUp() throws Exception {
+        super.setUp();
```
Comment (julianseeger) [inline src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java]: Is this neccessary? Try if the parent setUp() is called anyways.

File: src/main/java/de/qabel/desktop/util/QuotaUtil.java [hunk 15]
```diff
@@ -0,0 +1,21 @@
...
+import static humanize.Humanize.binaryPrefix;
+
+public class QuotaUtil {
+
+    public static int ratioByDiff(long usedQuota, long availableQuota) {
+        return (int) (usedQuota / (double) availableQuota * 100);
+    }
+
+    public static String getQuotaDescription(QuotaState q, String freeLabel) {
+        String seperator = " " + freeLabel + " / ";
```
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/util/QuotaUtil.java]: This is easier to customize if you use a translation with placeholder. "%s free / %s" or similar. There should already be examples for that.

File: src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java [hunk 16]
```diff
@@ -1,25 +1,44 @@
...
+    }
+
+    @Test
+    public void testFillQuotaInformation() throws IOException, QblInvalidCredentials {
+        LayoutController controller = createController();
+        assertEquals("30%", controller.quota.getText());
+        assertEquals(30, (int) controller.quotaBar.getMinWidth());
+        assertEquals("667.57 MB free / 953.67 MB", controller.quotaDescription.getText());
```
Comment (julianseeger) [inline src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java]: According to the mockup, there should be one digit after the comma. And imho you should add a test that we use the i18n support of mfornos/humanize correctly (just add a test that sets the locale to de_DE and assert for the correct size format)

File: src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java [hunk 17]
```diff
@@ -2,43 +2,43 @@
...
-        super.setUp();
-    }
-
     @Test
     public void testFillQuotaInformation() throws IOException, QblInvalidCredentials {
+        Locale.setDefault(new Locale("te", "ST"));
         LayoutController controller = createController();
         assertEquals("30%", controller.quota.getText());
         assertEquals(30, (int) controller.quotaBar.getMinWidth());
         assertEquals("667.57 MB free / 953.67 MB", controller.quotaDescription.getText());
```
Comment (audax) [inline src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java]: Still 2 digits after the period

Comment (nnice) [inline src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java]: @mr-gosh is fine with 2 digits

**Comment by julianseeger** [comment]
The progressbar doesn't work (at lest on 0% usage):
image

**Comment by julianseeger** [comment]
I don't see a test for the error-on-getQuota case. What happens? It seems to work but there should be an automated test for this especially because it's very hard to reproduce without modifying the code

File: build.gradle [hunk 18]
```diff
@@ -98,7 +98,8 @@ dependencies {
     compile 'javax.inject:javax.inject:1'                    //Apache License http://mvnrepository.com/artifact/javax.inject/javax.inject/1
     compile 'com.airhacks:afterburner.fx:1.7.+'              //Apache License https://github.com/AdamBien/afterburner.fx
 
-    compile 'com.github.Qabel:qabel-core:0.12.1'
+//    compile 'com.github.Qabel:qabel-core:0.14'
+    compile 'com.github.nnice:qabel-core:2d9889ac3bc328f50e7a03bb7d580940920097c3'
```
Comment (julianseeger) [inline build.gradle]: XXX

File: src/test/java/de/qabel/desktop/ui/contact/ContactControllerTest.java [hunk 19]
```diff
@@ -166,7 +167,7 @@ public void importValidContactAfterFailedImport() throws Exception {
         controller.importContacts(c1.toFile());
         try {
             controller.importContacts(c1.toFile());
-            fail("duplicate import failed, cannot continue test");
+            fail("expecting EntityExistsException on duplicate contact");
         } catch (Exception ignored) {}
```
Comment (enkore) [inline src/test/java/de/qabel/desktop/ui/contact/ContactControllerTest.java]: If only EntityExistsException is expected, then better only catch that specific exception to avoid hiding errors that may lurk in the dark :)

Comment (nnice) [inline src/test/java/de/qabel/desktop/ui/contact/ContactControllerTest.java]: good point, 
well then i have to catch out the PersistenceException because EntityExists... is part of it

**Comment by julianseeger** [comment]
> This branch has conflicts that must be resolved

File: src/main/java/de/qabel/desktop/daemon/sync/worker/index/sqlite/DesktopSyncDatabase.java [hunk 20]
```diff
@@ -11,10 +11,22 @@ public DesktopSyncDatabase(Connection connection) {
...
     @Override
     public AbstractMigration[] getMigrations(Connection connection) {
         return new AbstractMigration[]{
             new Migration1462872507CreateSyncedState(connection)
         };
     }
+
+    @Override
+    public long getVersion() {
+        return version;
```
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/daemon/sync/worker/index/sqlite/DesktopSyncDatabase.java]: from the interface docblock:
> Read the version of the last executed migration from the database

this is probably the implementation you need (read/write from/to the PRAGMA USER_VERSION):
https://github.com/Qabel/qabel-core/commit/48e3ec5d25e667c0d08746c12ddb348fdc7906d8#diff-37c5d765251f069dffba32c1c1543d78L25

File: src/main/java/de/qabel/desktop/daemon/sync/worker/index/sqlite/DesktopSyncDatabase.java [hunk 21]
```diff
@@ -11,10 +11,22 @@ public DesktopSyncDatabase(Connection connection) {
         super(connection);
     }
 
+    private long version = 0;
```
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/daemon/sync/worker/index/sqlite/DesktopSyncDatabase.java]: if you would need this long, then you could omit the default value because an uninitialized long has the value `0`

File: src/main/java/de/qabel/desktop/util/QuotaUtil.java [hunk 22]
```diff
@@ -0,0 +1,29 @@
...
+        String totalQuota = binaryPrefix(q.getQuota(), Locale.getDefault());
+
+        return MessageFormat.format(quotaDescriptionPattern, usedQuota, totalQuota);
+    }
+
+    public static int getUsedRatio(QuotaState q) {
+        if (q.getSize() == q.getQuota()) {
+            return 0;
+        }
+        return (int) (q.getSize() / (double) q.getQuota() * 100);
```
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/util/QuotaUtil.java]: This methods name is misleading. Ration in percent ... looks like a view-thing to transform it into percent.

File: src/main/resources/de/qabel/desktop/ui/layout.fxml [hunk 23]
```diff
@@ -29,10 +29,10 @@
                                                 <Label fx:id="alias" text="Guy Pearce Longerman" styleClass="alias"/>
                                                 <Label fx:id="mail" text="guy@pearce.com" styleClass="mail"
                                                        style="-fx-font-size: 0.8em"/>
-                                                <BorderPane styleClass="quotaBlock" visible="false">
+                                                <BorderPane fx:id="quotaBlock" styleClass="quotaBlock" visible="true">
                                                     <right>
                                                         <Label fx:id="quota" BorderPane.alignment="CENTER"
-                                                               text="24%" styleClass="quota"
+                                                               text="0" styleClass="quota"
```
Comment (julianseeger) [inline src/main/resources/de/qabel/desktop/ui/layout.fxml]: `""` or anything with `%` would be a better default than `"0"` wouldn't it?

File: src/main/java/de/qabel/desktop/daemon/sync/worker/index/sqlite/DesktopSyncDatabase.java (hunk 21 above)
Comment (nnice) [inline src/main/java/de/qabel/desktop/daemon/sync/worker/index/sqlite/DesktopSyncDatabase.java]: good to know tho, thanks

File: src/main/resources/de/qabel/desktop/ui/layout.fxml (hunk 23 above)
Comment (nnice) [inline src/main/resources/de/qabel/desktop/ui/layout.fxml]: sure thing.

**Comment by julianseeger** [comment]
Tested locally and works fine.

**Comment by enkore** [comment]
Project build is also green with this merged..... how?
