### PR TITLE
make crashreport URL configurable

### LINKED ISSUE #279: make crashreport URL configurable
To distinguish between update channels (closed beta / open beta / release or similar) and include the qabel client version in crashreports.
Without this it will be impossible to track, when a bug was introduced and if a pending update fixes it.

### PR DESCRIPTION
**Pull request by nnice**
resolves #279

### CODE REVIEW

File: src/test/java/de/qabel/desktop/hockeyapp/CrashReporterClientTest.java [hunk 1]
```diff
@@ -14,7 +14,8 @@
 public class CrashReporterClientTest {
 
     private CloseableHttpClientStub httpClientStub = new CloseableHttpClientStub();
-    private HockeyAppRequestBuilder requestBuilder = new HockeyAppRequestBuilder("1.1", httpClientStub);
+
+    private HockeyAppRequestBuilder requestBuilder = new HockeyAppRequestBuilder("https://rink.hockeyapp.net/api/2/apps/", "1.1", httpClientStub);
```
Comment (julianseeger) [inline src/test/java/de/qabel/desktop/hockeyapp/CrashReporterClientTest.java]: wrap that line or use a shorter url (it's stubbed so feel free to use `"url"` as the hockeyapp base url)

File: src/test/java/de/qabel/desktop/hockeyapp/FeedbackClientTest.java [hunk 2]
```diff
@@ -18,7 +18,7 @@
 
     private CloseableHttpClientStub httpClientStub = new CloseableHttpClientStub();
 
-    private HockeyAppRequestBuilder requestBuilder = new HockeyAppRequestBuilder("1.1", httpClientStub);
+    private HockeyAppRequestBuilder requestBuilder = new HockeyAppRequestBuilder("https://rink.hockeyapp.net/api/2/apps/", "1.1", httpClientStub);
```
Comment (julianseeger) [inline src/test/java/de/qabel/desktop/hockeyapp/FeedbackClientTest.java]: wrap that line or use a shorter url

File: src/test/java/de/qabel/desktop/hockeyapp/HockeyAppRequestBuilderTest.java [hunk 3]
```diff
@@ -1,14 +1,17 @@
...
 import org.junit.Test;
 
 import static org.junit.Assert.assertEquals;
 
 public class HockeyAppRequestBuilderTest {
 
     private CloseableHttpClientStub httpClientStub = new CloseableHttpClientStub();
-    private HockeyAppRequestBuilder requestBuilder = new HockeyAppRequestBuilder("1.1", httpClientStub);
+
+    private HockeyAppRequestBuilder requestBuilder = new HockeyAppRequestBuilder("https://rink.hockeyapp.net/api/2/apps/", "1.1", httpClientStub);
```
Comment (julianseeger) [inline src/test/java/de/qabel/desktop/hockeyapp/HockeyAppRequestBuilderTest.java]: same here..

File: src/test/java/de/qabel/desktop/hockeyapp/VersionClientTest.java [hunk 4]
```diff
@@ -19,7 +19,7 @@
     private static final String VERSION_1_1 = "1.1";
 
     private CloseableHttpClientStub httpClient = new CloseableHttpClientStub();
-    private HockeyAppRequestBuilder requestBuilder = new HockeyAppRequestBuilder(VERSION_1_0, httpClient);
+    private HockeyAppRequestBuilder requestBuilder = new HockeyAppRequestBuilder("https://rink.hockeyapp.net/api/2/apps/", VERSION_1_0, httpClient);
```
Comment (julianseeger) [inline src/test/java/de/qabel/desktop/hockeyapp/VersionClientTest.java]: +
