### PR TITLE
#304 stucked transfers

### LINKED ISSUE #186: loading bar (navi) not always hiding when finished
https://rink.hockeyapp.net/manage/apps/289338/feedback/444986

### LINKED ISSUE #232: handle disconnects during transfers
dis- / reconnects during downloads (and probably also during uploads) seems to stall the TransferManager Threads => no further transfers are executed

### LINKED ISSUE #262: [build] stabilize instable tests
there are some tests that fail by random on jenkins:

https://jenkins.prae.me/job/qabel-desktop/153/console
```
de.qabel.desktop.ui.remotefs.RemoteFSGuiTest > unshareFile FAILED
    java.lang.RuntimeException at RemoteFSGuiTest.java:142
        Caused by: java.lang.NullPointerException at RemoteFSGuiTest.java:142
```

https://jenkins.prae.me/job/qabel-desktop/155/console
```
de.qabel.desktop.ui.remotefs.RemoteFSGuiTest > unshareFile FAILED
    java.lang.RuntimeException at RemoteFSGuiTest.java:142
        Caused by: java.lang.NullPointerException at RemoteFSGuiTest.java:142
```

https://jenkins.prae.me/job/qabel-desktop/158/console
```
de.qabel.desktop.ui.remotefs.FilterableFolderTreeItemTest > showsFilterMatches FAILED
    java.lang.AssertionError at FilterableFolderTreeItemTest.java:87
```

### LINKED ISSUE #273: sync: bulk commits
When uploading (especially syncing) many small files, the autocommit after each change slows things down.

Example with source code:
average duration for file upload: 200ms
average duration for directory creation (upload): 500ms
average duration for commit: 500ms

For directories, the autocommit wastes 50% time (wow, this result is plausible) and for small files it even wastes > 60% time.

To implement bulk commits a strategy should be discussed when to commit to minimize the conflict potential and be up2date enough (like wait after a change as long as the remote polling interval and if no other change was made, commit the dm).

### LINKED ISSUE #274: show number of transfers on progress
on both progress bars (total in navi and per syncConfig in sync overview), the total number of transactions and the number of outstanding (or done) transactions should be shown. This is already shown in the mockups and would be very useful to see progress when up-/downloading many (small) files.

### LINKED ISSUE #296: sync: file ignore patterns broken
Somtimes, the temporary download (or decryption) files appear in the logs of the transfer manager. They should match the ignore pattern `.*~` and shouldn't be synced at all. So this feature is somehow broken which could have bad effects when files are synced wich backslashes etc. Pretty important imho

### LINKED ISSUE #316: data loss on DM conflict
see https://github.com/Qabel/qabel-android/issues/421

if the DM detects a new remote DM on commit, it doesn't merge all actions (at least new folders, deleted folders and deleted files are missing). This leads to data loss and files in the dm that no longer have a block (thus, can't be downloaded)

### PR DESCRIPTION
**Pull request by julianseeger**
A couple of things to fix the phenomena that syncs get stucked or freeze the GUI.
 * http connections of up- and downloads are now closed (at all)
 * switched most collections involved in transfers and syncs to thread safe versions
 * GUI-near code caches more actions to lower load of PlatformThread (less GUI freezes)

Do reproduce it (because I couldn't reproduce it in test-like behavior or load) I had to add some verbosity features and features to increase the throughput. Those features have been prototyped and I'm now rewriting or at least reworking them to make them maintainable:

 
resolves #273 **sync: bulk commits** *(naive implementation but does it's job)*
resolves #316 **data loss on DM conflict**
resolves #232 **handle disconnects during transfers** *(logarithmic retry by apache commons httpclient, couldn't kill it yet)*
resolves #186 **loading bar (navi) not always hiding when finished**
resolves #296 **sync: file ignore patterns broken** *(think that issue may be wrong, was just logging stuff and seems to be gone, at least after this PR)*
resolves #274 **show number of transfers on progress**
resolves #262 (don't care about that other test...)

+ fixed the bug that sometimes, if you open the sync overview too fast after startup, the syncs don't show any progress (was because of the ui was initialized before a SyncDaemon was started and it couldn't handle that order)

and it looks much more like the mockup now, even cooler ;)

### CODE REVIEW

**Comment by julianseeger** [comment]
jenkins? would you please...!?

**Comment by julianseeger** [comment]
heisenbug vanished temporarily ( #262 )

**Comment by julianseeger** [comment]
Think I'm done here.
As soon as jenkins agrees, I'll remove the `[WIP]` and it can get merged

File: src/main/java/de/qabel/desktop/daemon/management/DefaultTransferManager.java [hunk 1]
```diff
@@ -63,7 +63,7 @@ public void cleanup() {
 
 	@Override
 	public void addUpload(Upload upload) {
-		logger.trace("upload added: " + upload.getSource() + " to " + upload.getDestination());
+		//logger.trace("upload added: " + upload.getSource() + " to " + upload.getDestination());
```
Comment (audax) [inline src/main/java/de/qabel/desktop/daemon/management/DefaultTransferManager.java]: *poke*

File: src/main/java/de/qabel/desktop/storage/ProgressInputStream.java [hunk 2]
```diff
@@ -35,7 +39,20 @@ private void add(long bytes) {
...
+
+	private void update() {
+		update(false);
+	}
+
+	private void update(boolean force) {
+		long now = System.currentTimeMillis();
+//		if (force || now < lastUpdate + 100) {
+//			return;
+//		}
```
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/ProgressInputStream.java]: *poke*

File: src/main/java/de/qabel/desktop/ui/transfer/TransactionIconRenderer.java [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+import de.qabel.desktop.daemon.management.Upload;
+import javafx.scene.image.Image;
+
+import java.util.function.Function;
+
+public class TransactionIconRenderer implements Function<Transaction, Image> {
+	private static final Image folderDownloadImg = new Image(TransactionIconRenderer.class.getResourceAsStream("/icon/add_folder.png"), 18, 18, true, true);
+	private static final Image folderUploadImg = new Image(TransactionIconRenderer.class.getResourceAsStream("/icon/folder-upload.png"), 18, 18, true, true);
+	private static final Image fileDownloadImg = new Image(TransactionIconRenderer.class.getResourceAsStream("/icon/download.png"), 18, 18, true, true);
+	private static final Image fileUploadImg = new Image(TransactionIconRenderer.class.getResourceAsStream("/icon/upload.png"), 18, 18, true, true);
```
Comment (audax) [inline src/main/java/de/qabel/desktop/ui/transfer/TransactionIconRenderer.java]: line length :)

File: src/main/java/de/qabel/desktop/ui/transfer/TransactionFxProgressCollectionModel.java [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+	private ObjectProperty<Transaction> currentTransaction = new SimpleObjectProperty<>();
+	private BooleanProperty running = new SimpleBooleanProperty(false);
+
+	public TransactionFxProgressCollectionModel(HasProgressCollection<?, Transaction> progress) {
+		super(progress);
+		onChange(this::update);
+	}
+
+	private void update(Transaction transaction) {
+		if (transaction == null || transaction.getState() != Transaction.STATE.RUNNING) {
```
Comment (audax) [inline src/main/java/de/qabel/desktop/ui/transfer/TransactionFxProgressCollectionModel.java]: When and why can the transaction be null?

File: src/main/java/de/qabel/desktop/ui/transfer/FxProgressModel.java [hunk 5]
```diff
@@ -28,7 +39,15 @@ public void setProgress(HasProgress progress) {
 		updateProgress();
 	}
 
+	long lastUpdate = 0;
+
 	private void updateProgress() {
-		Platform.runLater(() -> progressProperty.set(this.progress.getProgress()));
+		final double progress = this.progress.getProgress();
+		long now = System.currentTimeMillis();
+		if (progress != 1.0 && minimumUpdateDelay != null && now < lastUpdate + minimumUpdateDelay) {
```
Comment (audax) [inline src/main/java/de/qabel/desktop/ui/transfer/FxProgressModel.java]: Equals on float values? Can progress be > 1?

File: src/main/java/de/qabel/desktop/storage/command/DeleteFileChange.java [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+		if (file.isShared()) {
+			removeSharesFromIndex();
+			removeFileMetadata(dm);
+		}
+
+		return new FileDeletionResult(dm, file);
+	}
+
+	private void removeFileMetadata(DirectoryMetadata dm) throws QblStorageException {
+		AbstractNavigation.removeFileMetadata(file, writeBackend, dm);
```
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/command/DeleteFileChange.java]: It is weird to call a method on an abstract (at least by name) class.

File: src/main/java/de/qabel/desktop/storage/command/CreateFolderChange.java [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+public class CreateFolderChange implements DirectoryMetadataChange<ChangeResult<BoxFolder>> {
+	private CryptoUtils cryptoUtils = new CryptoUtils();
+	private String name;
+	private byte[] deviceId;
+	private final KeyParameter secretKey;
+
+	public CreateFolderChange(String name, byte[] deviceId) {
+		this.name = name;
+		this.deviceId = deviceId;
+		secretKey = cryptoUtils.generateSymmetricKey();
```
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/command/CreateFolderChange.java]: No need to save the secretKey since it is private and _only_ used in the execute method.

File: src/main/java/de/qabel/desktop/storage/cache/CachedBoxNavigation.java [hunk 8]
```diff
@@ -211,21 +229,23 @@ public BoxExternalReference share(QblECPublicKey owner, BoxFile file, String rec
...
-					Set<BoxFile> newFiles = new HashSet<>(nav.listFiles());
-					Set<BoxFile> changedFiles = new HashSet<>();
-
-					findNewFolders(oldFolders, newFolders);
-					findNewFiles(oldFiles, newFiles, changedFiles);
-					findDeletedFolders(oldFolders, newFolders);
-					findDeletedFiles(oldFiles, newFiles, changedFiles);
+				if (nav.isUnmodified()) {
+					DirectoryMetadata dm = nav.reloadMetadata();
+					if (!Arrays.equals(nav.getMetadata().getVersion(), dm.getVersion())) {
```
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/cache/CachedBoxNavigation.java]: A method "hasVersionChanged" would be nice

File: src/main/java/de/qabel/desktop/ui/transfer/TransactionFxProgressCollectionModel.java (hunk 4 above)
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/ui/transfer/TransactionFxProgressCollectionModel.java]: between two transfers (when the last one is finished and the new one hasn't been started yet)
extract method? ...

File: src/main/java/de/qabel/desktop/storage/StorageDownload.java [hunk 9]
```diff
@@ -1,16 +1,23 @@
...
+import java.io.Closeable;
+import java.io.IOException;
 import java.io.InputStream;
 
-public class StorageDownload {
+public class StorageDownload implements Closeable {
 	private InputStream inputStream;
 	private String mHash;
 	private long size;
+	private Closeable closeable;
```
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/StorageDownload.java]: Is this for a file handle?

File: src/main/java/de/qabel/desktop/ui/transfer/FxProgressModel.java (hunk 5 above)
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/ui/transfer/FxProgressModel.java]: maybe too much abstraction ... even >= 1 wouldn't help. T should be required to implement isDone or similar

File: src/main/java/de/qabel/desktop/storage/HttpReadBackend.java [hunk 10]
```diff
@@ -36,34 +36,34 @@ public StorageDownload download(String name, String ifModifiedVersion) throws Qb
...
-			throw new QblStorageException("Download error");
-		}
-		String modifiedVersion = response.getFirstHeader(HttpHeaders.ETAG).getValue();
+			CloseableHttpResponse response = httpclient.execute(httpGet);
+			try {
+				int status = response.getStatusLine().getStatusCode();
+				if ((status == 404) || (status == 403)) {
+					throw new QblStorageNotFound("File not found");
+				}
+				if (status == HttpStatus.SC_NOT_MODIFIED) {
```
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/HttpReadBackend.java]: Why do only use the HttpStatus constants here and not consistently everywhere or never?

File: src/main/java/de/qabel/desktop/storage/FolderNavigation.java [hunk 11]
```diff
@@ -39,9 +39,7 @@ protected void uploadDirectoryMetadata() throws QblStorageException {
 	public DirectoryMetadata reloadMetadata() throws QblStorageException {
 		logger.info("Reloading directory metadata");
 		// duplicate of navigate()
-		try {
-			StorageDownload download = readBackend.download(dm.getFileName(), directoryMetadataMHashes.get(Arrays.hashCode(dm.getVersion())));
-
+		try (StorageDownload download = readBackend.download(dm.getFileName(), directoryMetadataMHashes.get(Arrays.hashCode(dm.getVersion())))) {
```
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/FolderNavigation.java]: `directoryMetadataMHashes.get(Arrays.hashCode(dm.getVersion())))` could be moved into a seperate method.

File: src/main/java/de/qabel/desktop/storage/AbstractNavigation.java [hunk 12]
```diff
@@ -451,8 +506,10 @@ public synchronized void delete(BoxFolder folder) throws QblStorageException {
 			folderNav.delete(subFolder);
 		}
 		folderNav.commit();
-		dm.deleteFolder(folder);
-		deleteQueue.add(folder.getRef());
+		DeleteFolderChange deleteFolderChange = new DeleteFolderChange(folder);
+		DeleteFolderChange.FolderDeletionResult result = deleteFolderChange.execute(dm);
+		changes.add(deleteFolderChange);
+		deleteQueue.add(result.getDeletedBlockRef());
```
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/AbstractNavigation.java]: The Delete-command (DeleteFolder and DeleteFile) executions look very similar.

File: src/main/java/de/qabel/desktop/storage/AbstractNavigation.java [hunk 13]
```diff
@@ -248,8 +282,23 @@ private void autocommit() throws QblStorageException {
...
 
-		commit();
+		final long autocommitStart = System.currentTimeMillis();
+
+		scheduler.schedule(() -> {
+			try {
+				if (lastAutocommitStart != autocommitStart) {
+					return;
+				}
+				AbstractNavigation.this.commitIfChanged();
```
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/AbstractNavigation.java]: Having the scheduler code in AbstractNavigaton feels a bit weird.

File: src/main/java/de/qabel/desktop/storage/AbstractNavigation.java [hunk 14]
```diff
@@ -67,7 +81,10 @@ public synchronized AbstractNavigation navigate(BoxFolder target) throws QblStor
 			if (cryptoUtils.decryptFileAuthenticatedSymmetricAndValidateTag(indexDl, tmp, key)) {
 				DirectoryMetadata dm = DirectoryMetadata.openDatabase(
 						tmp, deviceId, target.ref, this.dm.getTempDir());
-				return new FolderNavigation(prefix, dm, keyPair, target.key, deviceId, readBackend, writeBackend, getIndexNavigation());
+				FolderNavigation folderNavigation = new FolderNavigation(prefix, dm, keyPair, target.key, deviceId, readBackend, writeBackend, getIndexNavigation());
```
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/AbstractNavigation.java]: <3 a linebreak here

File: src/main/java/de/qabel/desktop/storage/StorageDownload.java (hunk 9 above)
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/storage/StorageDownload.java]: For whatever you download (but in the current implementations it's a CloseableHTTPResponse ... that needs to be closed after all contents have been fetched ... or soon enough to not fill up the connection pool

File: src/main/java/de/qabel/desktop/storage/AbstractNavigation.java (hunk 13 above)
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/storage/AbstractNavigation.java]: ... we could move it to an autocommitStrategy that is injected. Could getting rid of the AUTOCOMMIT_DELAY thing easier. But that won't change much of who decides when to commit.
Ideas?

File: src/main/java/de/qabel/desktop/storage/AbstractNavigation.java (hunk 14 above)
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/storage/AbstractNavigation.java]: temporarily ok, but we have to talk about those n-parameter constructors once this stuff is moved to the core (or at least as much of it as possible) ...

File: src/main/java/de/qabel/desktop/ui/transfer/FxProgressModel.java (hunk 5 above)
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/ui/transfer/FxProgressModel.java]: nvm. of course we have total size and current (=transferred) size

File: src/main/java/de/qabel/desktop/storage/command/CreateFolderChange.java (hunk 7 above)
Comment (julianseeger) [inline src/main/java/de/qabel/desktop/storage/command/CreateFolderChange.java]: On conflict, the `execute()` method is executed at least twice (once on initial createFolder and the second time when it's reapplied to the reloaded DM).
If we use another key, the new (already uploaded) DM can't be read / decrypted, can it?

Comment (audax) [inline src/main/java/de/qabel/desktop/storage/command/CreateFolderChange.java]: Indeed.

File: src/main/java/de/qabel/desktop/storage/StorageDownload.java (hunk 9 above)
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/StorageDownload.java]: kk

File: src/main/java/de/qabel/desktop/storage/AbstractNavigation.java (hunk 13 above)
Comment (audax) [inline src/main/java/de/qabel/desktop/storage/AbstractNavigation.java]: The injected strategy thingy sounds reasonable and could be useful as soon as we need different strategies or at least have to change the strategy. For now it should be fine.
